apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server  
spec:
  replicas: {{ .Values.config.replicaCount }}
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: {{ .Values.config.image }}
          ports:
            - containerPort: {{ .Values.config.port }}
      initContainers:
      - name: wait-for-sql
        image: busybox
        command: ['sh', '-c', 'until nc -z mysql 3306; do echo "Waiting..."; sleep 5; done']
---

apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: {{ .Values.config.port }}
      targetPort: {{ .Values.config.port }}
  type: {{ .Values.config.type }}
