apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"  # Higher than MySQL
    "helm.sh/hook-delete-policy": before-hook-creation  
spec:
  replicas: {{ .Values.config.replicaCount }}
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: {{ .Values.config.image }}
          ports:
            - containerPort: {{ .Values.config.port }}
---

apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: {{ .Values.config.port }}
      targetPort: {{ .Values.config.port }}
  type: {{ .Values.config.type }}
