apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  labels:
    app: discovery-server
spec:
  replicas: {{ .Values.discovery.replicaCount }}
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: {{ .Values.discovery.image }}
        ports:
        - containerPort: {{ .Values.discovery.port }}
        
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  selector:
    app: discovery-server
  ports:
    - protocol: TCP
      port: {{ .Values.discovery.port }}
      targetPort: {{ .Values.discovery.port }}
  type: {{ .Values.discovery.type }}
