apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-server
  labels:
    app: tracing-server
spec:
  replicas: {{ .Values.tracing.replicaCount }}
  selector:
    matchLabels:
      app: tracing-server
  template:
    metadata:
      labels:
        app: tracing-server
    spec:
      containers:
      - name: tracing-server
        image: {{ .Values.tracing.image }}
        ports:
        - containerPort: {{ .Values.tracing.port }}
        env:
        - name: SPRING_APPLICATION_NAME
          value: tracing-server 
        - name: SPRING_PROFILES_ACTIVE
          value: docker      
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://discovery-server:8761/eureka/
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "*"          
        - name: SERVER_PORT
          value: "9411"
        
---
apiVersion: v1
kind: Service
metadata:
  name: tracing-server
spec:
  selector:
    app: tracing-server
  ports:
    - protocol: TCP
      port: {{ .Values.tracing.port }}
      targetPort: {{ .Values.tracing.port }}
  type: {{ .Values.tracing.type }}
