apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
  labels:
    app: visits-service
spec:
  replicas: {{ .Values.visits.replicaCount }}
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
      - name: visits-service
        image: {{ .Values.visits.image }}
        ports:
        - containerPort: {{ .Values.visits.port }}
      initContainers:
      - name: wait-for-api
        image: busybox
        command: ['sh', '-c', 'until nc -z api-gateway 8080; do echo "Waiting..."; sleep 5; done']
---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
spec:
  selector:
    app: visits-service
  ports:
  - protocol: TCP
    port: {{ .Values.visits.port }}
    targetPort: {{ .Values.visits.port }}
  type: {{ .Values.visits.type }}
