apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-ingress
  annotations: {}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # - path: /eureka
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: discovery-server
          #       port:
          #         number: 8761

          # - path: /grafana
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: grafana-server
          #       port:
          #         number: 3000

          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tracing-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /zipkin
            pathType: Prefix
            backend:
              service:
                name: tracing-server
                port:
                  number: 9411

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: admin-server
                port:
                  number: 9091

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eureka-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /eureka-service/$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/app-root: /eureka/
    nginx.ingress.kubernetes.io/configuration-snippet: |
      sub_filter_once off;
      sub_filter 'href="/' 'href="/eureka/';
      sub_filter 'src="/' 'src="/eureka/';
      sub_filter '"/eureka/eureka/' '"/eureka/';
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /eureka(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: discovery-server
            port:
              number: 8761


