apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: admin-server
            port:
              number: 9091
              
      - path: /eureka
        pathType: Prefix
        backend:
          service:
            name: discovery-server
            port:
              number: 8761

      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 8080

       - path: /zipkin
         pathType: Prefix
         backend:
          service:
            name: tracing-server
            port:
              number: 9411

        - path: /grafana
          pathType: Prefix
          backend:
           service:
            name: grafana-server
            port:
              number: 3000
      

           
