apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-eureka
  namespace: petclinic
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: discovery-server
  rules:
    # Allow browser access through Ingress Gateway
    - from:
        - source:
            namespaces: ["istio-system"]
      to:
        - operation:
            methods: ["GET"]
            paths: ["/", "/eureka", "/eureka/", "/eureka/*", "/eureka/css/*", "/eureka/js/*"]

    # Allow Eureka clients (services) to register/heartbeat
    - from:
        - source:
            namespaces: ["petclinic"]
      to:
        - operation:
            methods: ["GET", "POST", "PUT", "DELETE"]
            paths: ["/eureka/apps", "/eureka/apps/*"]

    # Eureka self-communication (optional but good to keep)
    - from:
        - source:
            namespaces: ["petclinic"]
      to:
        - operation:
            methods: ["GET"]
            paths: ["/eureka/apps", "/eureka/apps/*"]
