# apiVersion: security.istio.io/v1beta1
# kind: AuthorizationPolicy
# metadata:
#   name: allow-all-to-eureka
#   namespace: petclinic
# spec:
#   selector:
#     matchLabels:
#       app: discovery-server
#   rules:
#     - {}
    
# istio/eureka-auth-policy.yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-all-to-eureka
  namespace: petclinic
spec:
  selector:
    matchLabels:
      app: discovery-server
  rules:
    - from:
        - source:
            namespaces: ["petclinic"]
      to:
        - operation:
            ports: ["8761"]


