apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-eureka
  namespace: petclinic
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: discovery-server
  rules:
    # 1. Allow GET from Istio Ingress Gateway for Eureka dashboard
    - from:
        - source:
            principals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]
      to:
        - operation:
            methods: ["GET"]
            paths: ["/", "/eureka", "/eureka/", "/eureka/*", "/eureka/css/*", "/eureka/js/*"]

    # 2. Allow Eureka clients in petclinic namespace to register, heartbeat
    - from:
        - source:
            namespaces: ["petclinic"]
      to:
        - operation:
            methods: ["GET", "POST", "PUT", "DELETE"]
            paths: ["/eureka/apps", "/eureka/apps/*"]

    # 3. Allow Eureka to talk to itself
    - from:
        - source:
            principals: ["cluster.local/ns/petclinic/sa/discovery-server"]
      to:
        - operation:
            methods: ["GET"]
            paths: ["/eureka/apps", "/eureka/apps/*"]
