apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-eureka
  namespace: petclinic
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: discovery-server  # Targets Eureka server pods
  rules:
    # 1. Allow Ingress Gateway (dashboard access)
    - from:
        - source:
            principals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"] 
      to:
        - operation:
            methods: ["GET"]
            paths: ["/", "/eureka*", "/eureka/css/*", "/eureka/js/*"]  # Added web assets

    # 2. Allow service registration/heartbeats (critical fix!)
    - from:
        - source:
            namespaces: ["petclinic"]
      to:
        - operation:
            methods: ["GET", "POST", "PUT", "DELETE"]
            paths: ["/eureka/apps*"]  # Fixed path pattern (no duplicate /eureka)

    # 3. Allow Eureka self-communication (optional)
    - from:
        - source:
            principals: ["cluster.local/ns/petclinic/sa/discovery-server"]
      to:
        - operation:
            methods: ["GET"]
            paths: ["/eureka/apps*"]
