apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-eureka
  namespace: petclinic
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: discovery-server
  rules:
    # Allow GET from istio ingress gateway for dashboard access
    - from:
        - source:
            namespaces: ["istio-system"]
      to:
        - operation:
            methods: ["GET"]
            paths: ["/eureka", "/eureka/*"]
    # Allow GET, PUT, POST from petclinic namespace pods (Eureka clients)
    - from:
        - source:
            namespaces: ["petclinic"]
      to:
        - operation:
            methods: ["GET", "PUT", "POST"]
            paths: ["/eureka", "/eureka/*"]
    # Allow discovery-server to talk to itself
    - from:
        - source:
            principals: ["cluster.local/ns/petclinic/sa/discovery-server"]
      to:
        - operation:
            methods: ["GET"]
            paths: ["/eureka", "/eureka/*"]
this is my current file
