apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-eureka
  namespace: petclinic
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: discovery-server  # Make sure this matches your actual pod labels
  rules:
    # 1. Allow access from Istio Ingress Gateway (browser/dashboard)
    - from:
        - source:
            # Use a wildcard for ingress gateway if unsure of SA
            namespaces: ["istio-system"]
      to:
        - operation:
            methods: ["GET"]
            paths: ["/", "/eureka", "/eureka/*", "/eureka/css/*", "/eureka/js/*"]

    # 2. Allow Eureka clients to register/heartbeat
    - from:
        - source:
            namespaces: ["petclinic"]
      to:
        - operation:
            methods: ["GET", "POST", "PUT", "DELETE"]
            paths: ["/eureka/apps", "/eureka/apps/*"]

    # 3. Allow Eureka server to talk to itself (replication, if needed)
    - from:
        - source:
            principals: ["cluster.local/ns/petclinic/sa/discovery-server"]
      to:
        - operation:
            methods: ["GET", "POST", "PUT"]
            paths: ["/eureka/apps", "/eureka/apps/*"]
