apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-eureka
  namespace: petclinic
spec:
  selector:
    matchLabels:
      app: discovery-server
  rules:
  - from:
    - source:
        namespaces: ["petclinic"]
