apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-eureka
  namespace: petclinic
spec:
  selector:
    matchLabels:
      app: discovery-server
  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/petclinic/sa/api-gateway"
              - "cluster.local/ns/petclinic/sa/customers-service"
              - "cluster.local/ns/petclinic/sa/order-service"
              - "cluster.local/ns/petclinic/sa/admin-server"
              - "cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"
      to:
        - operation:
            methods: ["GET", "POST", "PUT", "DELETE"]
            paths: 
              - "/eureka/apps*"
              - "/eureka/eureka/apps*"
              - "/eureka/*"
