apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: petclinic-destinationrule
  namespace: petclinic
spec:
  host: "*.petclinic.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE  # Disables mutual TLS
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp: 
        maxConnections: 100
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 100
    # Moved headers to the correct location
    headers:
      request:
        add:
          Connection: keep-alive
    outlierDetection:
      consecutiveErrors: 5
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
