apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: discovery-server-dr
  namespace: petclinic
spec:
  host: discovery-server.petclinic.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
