apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: default-mtls
  namespace: petclinic
spec:
  host: "*.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
