# Global settings
global:
  imagePullPolicy: IfNotPresent
  env: prod

# Config Server
configServer:
  enabled: true
  image: "my-registry/config-server:latest"
  port: 8888
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"

# MySQL (Bitnami)
mysql:
  enabled: true
  image: mysql:8.0
  port: 3306
  rootPassword: petclinic
  database: petclinic
  user: petclinic
  userPassword: petclinic
  accessMode: ReadWriteOnce
  size: 1Gi
  hostPath: /home/vishesh/petclinic/kubernetes/mysql-data
  type: ClusterIP

# Other Microservices (example for customers-service)
customersService:
  image: "my-registry/customers-service:latest"
  port: 8080
  configServerUrl: "http://config-server:8888"
