# Global settings
global:
  imagePullPolicy: IfNotPresent
  env: prod

# Config Server
config:
  enabled: true
  image: "vishesh/config-server:latest"
  port: 8888
  replicaCount: 1
  type: ClusterIP

  # discovery Server
discovery:
  enabled: true
  image: "vishesh/discovery-server:latest"
  port: 8761
  replicaCount: 1
  type: ClusterIP

# mysql
mysql:
  enabled: true
  image: mysql:8.0
  port: 3306
  rootPassword: petclinic
  database: petclinic
  user: petclinic
  userPassword: petclinic
  accessMode: ReadWriteOnce
  size: 1Gi
  hostPath: /home/vishesh/petclinic/kubernetes/mysql-data
  type: ClusterIP

# Other Microservices (example for customers-service)
customersService:
  image: "my-registry/customers-service:latest"
  port: 8080
  configServerUrl: "http://config-server:8888"
