# Global settings
global:
  imagePullPolicy: IfNotPresent
  env: prod

# Config Server
config:
  enabled: true
  image: "visheshvishu/config-server:latest"
  port: 8888
  replicaCount: 1
  type: ClusterIP

  # discovery Server
discovery:
  enabled: true
  image: "visheshvishu/discovery-server:latest"
  port: 8761
  replicaCount: 1
  type: ClusterIP

  # admin Server
admin:
  enabled: true
  image: "visheshvishu/admin-server:latest"
  port: 9091
  replicaCount: 1
  type: ClusterIP

   # api gateway
api:
  enabled: true
  image: "visheshvishu/api-gateway:latest"
  port: 8080
  replicaCount: 1
  type: ClusterIP

   # tracing server
api:
  enabled: true
  image: "openzipkin/zipkin"
  port: 9411
  replicaCount: 1
  type: ClusterIP

# mysql
mysql:
  enabled: true
  image: mysql:8.0
  port: 3306
  rootPassword: petclinic
  database: petclinic
  user: petclinic
  userPassword: petclinic
  accessMode: ReadWriteOnce
  size: 1Gi
  hostPath: /home/vishesh/petclinic/kubernetes/mysql-data
  type: ClusterIP

  # customers service
customers:
  enabled: true
  image: "visheshvishu/customers-service:latest"
  port: 8081
  replicaCount: 1
  type: ClusterIP

  # visits service
visits:
  enabled: true
  image: "visheshvishu/visits-service:latest"
  port: 8082
  replicaCount: 1
  type: ClusterIP

    # vets service
vets:
  enabled: true
  image: "visheshvishu/vets-service:latest"
  port: 8083
  replicaCount: 1
  type: ClusterIP
